version: '3'
services:
  db:
    ports:
      - 27018:27017
    restart: on-failure
    container_name: mashgin-db
    image: mongo:latest
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./resources/sample-menu.json:/docker-entrypoint-initdb.d/sample-menu.json
      - ./.data-volumes/database/.data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: mashgin-checkout-api-123
      MONGO_INITDB_DATABASE: checkout-db
  api:
    container_name: mashgin-api
    build: ./api/
    volumes:
      - ./resources/sample-images/:/docker-entrypoint-initfiles.d/images/
      - ./.data-volumes/files/:/files
    environment:
      DB_HOST: db
      DB_PORT: 27017
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: 'npm start'
  frontend:
    container_name: mashgin-frontend
    build: ./frontend/
    environment:
      API_URL: http://localhost:3000
    ports:
      - '3001:3000'
    command: 'npm start'
