version: '3'
services:
  api:
    volumes:
      - ./api/:/api/
    command: 'npm run start:dev'
  frontend:
    environment:
      - ENVIRONMENT=dev
    volumes:
      - ./frontend/:/frontend/
    command: 'npm run start:dev'
